### PR TITLE
minor patches split up

### PR DESCRIPTION
**Pull request by idnovic**
I cleaned it up a bit.
You now have single commits.

Screensaver function did not work for me so I removed it.

-Install guide
-Added desktop files
-Removed screensaver function
-Added temporarly allow function
-Changed allow to permanent allow
-Compile py as pyc for performance
-Set notification timeout to 10 seconds
-And more...

### CODE REVIEW

**Comment by 6E006B** [comment]
Thanks for the PR and your contribution.
I will cherry pick and apply some of your commits.
Though I do not concur with all of your proposed changes.
It's unfortunate that the screensaver related code does not work for your configuration.
Does the screensaver related code break the general functionality for you?
It does work for me and if it brakes for you, I would rather have a check in place, if it will work or not and omit this part programatically in case incompatibility is observed.
As for the installation instructions, we should add an installer.
Yet for now it's better than nothing, I will just have to change the url ;)

**Comment by idnovic** [comment]
That sound good. Originally I deleted the screensaver code. I thought maybe just comment it out this time. 

By it does not work for me I mean I attached a HID device, the popup appeared but the screen never locked. Gnome on Wayland. Also I see only a benefit while the user is not at his device but forgot to lock it. 

I need to add that I am running a patched version of gnome-shell and mutter with cherry  commits. It is possible that the problem is on my side.

But for me I did prefer to be asked about HID devices instead of the lockscreen. 
I tried s dual mode which failed. The try was to implant the screensaver without timeout set, but before the screensaver a device popup to allow a device with 5 second timeout.

My idea was if the user allows the device do not load the screensaver.

**Comment by 6E006B** [comment]
Okay, I have made the HID screen lock stuff configurable among a few other things.

The intention behind this locking is to have a backup solution when your input device brakes making it possible to use a USB one to regain access to your system.
And actually the implementation should be what you describe.
After hid-screenlock-timeout there is a check whether the device was allowed in the mean time and if so, don't lock the screen.

**Comment by idnovic** [comment]
But the original code did not ask the user to allow the device. It only displayed a warning message. So the user was left with a locked screen for new devices.

I will try the new version in the following days.

Just to add a comment, I intentionally wrote the name of usbguard all upper case because of the original qt GUI. I wanted a simple manner to differentiate the two. :)

Maybe edit the icon. Currently, the usbguard project dropped the qt GUI but they want to add a new GUI as external package.

**Comment by muelli** [comment]
>  Currently, the usbguard project dropped the qt GUI but they want to add a new GUI as external package.

note that we're trying to integrate USBGuard into the GNOME session: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/merge_requests/75

**Pull request closed without merging**
